import matplotlib.pyplot as plt


class Plot(object):

    def manipulate_data(self, output_dict):
        output_dict ={'arXie-Bot': [{'chat.post.Message': []}], 'carebot': [{'chat.post.Message': []}], 'charlesbot': [{'auth.test': '[]'}, {'rtm.connect': "['client']"}, {'users.info': "['users:read']"}], 'cloud-functions': [], 'code-pipeline-slack': [{'channels.list': "['channels:read']"}, {'channels.history': "['channels:history']"}, {'chat.post.Message': []}, {'chat.update': "['chat:write', 'chat:write:bot', 'chat:write:user']"}], 'hogwarts': [{'rtm.connect': "['client']"}, {'chat.post.Message': []}, {'files.upload': '[]'}], 'honey': [{'rtm.connect': "['client']"}, {'chat.post.Message': []}], 'karura': [], 'kubebot': [], 'omnibot': [], 'PokemonGo-SlackBot': [], 'pyconjpbot': [{'users.info': "['users:read']"}, {'im.open': "['im:write']"}, {'users.list': "['users:read']"}, {'groups.list': "['groups:read']"}, {'channels.info': "['channels:read']"}, {'users.get.Presence': []}], 'python-webpage-monitor-slackbot': [{'rtm.connect': "['client']"}], 'slack-machine': [{'chat.post.Message': []}, {'chat.post.Ephemeral': []}, {'reactions.add': "['reactions:write']"}, {'conversations.list': "['channels:read', 'groups:read', 'im:read', 'mpim:read']"}, {'conversations.info': "['channels:read', 'groups:read', 'im:read', 'mpim:read']"}, {'im.close': "['im:write']"}, {'im.open': "['im:write']"}], 'slackbot': [{'rtm.connect': "['client']"}, {'chat.post.Message': []}, {'channels.history': "['channels:history']"}, {'im.history': "['im:history']"}, {'users.list': "['users:read']"}, {'rtm.start': "['client']"}, {'im.open': "['im:write']"}, {'users.get.Presence': []}, {'files.list': "['files:read']"}, {'channels.join': "['channels:write']"}, {'groups.list': "['groups:read']"}, {'channels.info': "['channels:read']"}, {'channels.invite': "['channels:write']"}, {'groups.invite': "['groups:write']"}, {'files.upload': '[]'}, {'reactions.add': "['reactions:write']"}], 'slackbot-iot': [{'users.list': "['users:read']"}, {'rtm.connect': "['client']"}, {'chat.post.Message': []}], 'slackbot-python': [], 'slackbot-workout': [{'channels.list': "['channels:read']"}, {'channels.info': "['channels:read']"}, {'users.info': "['users:read']"}, {'users.get.Presence': []}]}
        for key in output_dict.keys():
            print(key)
            print(output_dict[key])
